### PR TITLE
Feat: Add stop command

### PR DESCRIPTION
**Pull request by Fabian-Fynn**
As alias for shutdown

### CODE REVIEW

**Comment by nsams** [comment]
should we rename the command?

**Comment by Fabian-Fynn** [comment]
I have no opinion on this. @kaufmo suggested adding it as alias

**Review by kaufmo — APPROVED** [review]

**Comment by nsams** [comment]
stop is easier to guess than shutdown, and I don't see a reason for two commands that do the same.

**Comment by Fabian-Fynn** [comment]
Ok I'll remove the shutdown command then

**Review by nsams — APPROVED** [review]

**Pull request merged**
