### PR TITLE
Add aliases for status and shutdown

### PR DESCRIPTION
**Pull request by thomasdax98**
status and shutdown are such long words. Therefore, I suggest adding the shortcuts `list` and `ls` (for `status`) and `kill` (for `shutdown`).

### CODE REVIEW

**Review by Fabian-Fynn — APPROVED** [review]
👍

**Review by Fabian-Fynn — CHANGES_REQUESTED** [review]
Please add your changes to the changelog

**Comment by nsams** [comment]
I'm against "del" as shtudown doesn't delete anyting.

**Comment by Fabian-Fynn** [comment]
> I'm against "del" as shtudown doesn't delete anyting.

How about "sd" or "stop" for shutdown?

**Comment by nsams** [comment]
stop we have already. sd... i don't know, not a common thing

**Comment by Fabian-Fynn** [comment]
"halt" would be fitting. It's also a common command

**Comment by johnnyomair** [comment]
Maybe kill?

**Comment by nsams** [comment]
halt seems appropriate. However I'm sure if we really need a alias just for the sake of having one.

@thomasdax98 what do you think?

**Comment by thomasdax98** [comment]
@nsams In my opinion, `shutdown` is too long and unhandy to type. I prefer short commands. 

`kill` is good in my opinion

**Comment by nsams** [comment]
I'm not sure about `kill`. I could think it's more like stop, as stop actually kills a process.

halt is better and also has 4 chars :)

**Comment by Fabian-Fynn** [comment]
@thomasdax98 I also prefer `halt`

**Review by Fabian-Fynn — APPROVED** [review]

**Comment by johnnyomair** [comment]
@thomasdax98 please fix conflicts

**Pull request merged**
